---
- name: set url for latest version
  set_fact:
    dynatrace_oneagent_installer_url: https://{{ dynatrace_environment_url }}/api/v1/deployment/installer/agent/{{ dynatrace_oneagent_install_url_key }}/default/latest?Api-Token={{ dynatrace_paas_token }}&arch=x86
  when: dynatrace_oneagent_version == 'latest'

- name: set url for specific version
  set_fact:
    dynatrace_oneagent_installer_url: https://{{ dynatrace_environment_url }}/api/v1/deployment/installer/agent/{{ dynatrace_oneagent_install_url_key }}/default/version/{{ dynatrace_oneagent_version }}?Api-Token={{ dynatrace_paas_token }}&arch=x86
  when: dynatrace_oneagent_version != 'latest'

- name: check if oneagent is installed | linux
  stat:
    path: "{{ dynatrace_oneagent_install_artifact }}"
  register: dynatrace_oneagent_state_file_linux
  when: ansible_system|lower == "linux"

- name: check if oneagent is installed | windows
  win_stat:
    path: "{{ dynatrace_oneagent_install_artifact }}"
  register: dynatrace_oneagent_state_file_windows
  when: ansible_system|lower == "win32nt"

- name: download dynatrace oneagent | linux
  get_url:
    url: "{{ dynatrace_oneagent_installer_url }}"
    dest: "{{ dynatrace_oneagent_install_script }}"
    validate_certs: "{{ dynatrace_oneagent_package_download_validate_certs }}"
  when: ansible_system|lower == "linux" and not dynatrace_oneagent_state_file_linux.stat.exists

- name: download dynatrace OneAgent | windows
  win_get_url:
    url: "{{ dynatrace_oneagent_installer_url }}"
    dest: "{{ dynatrace_oneagent_install_script }}"
    validate_certs: "{{ dynatrace_oneagent_package_download_validate_certs }}"
  when: ansible_system|lower == "win32nt" and not dynatrace_oneagent_state_file_windows.stat.exists