---
- name: Ensure Download directory exists
  ansible.builtin.file:
    path: "{{ oneagent_download_path }}"
    state: directory
    mode: "0755"
  when: not _oneagent_download_path_state.stat.exists

- name: Check if OneAgent installer exists
  ansible.builtin.stat:
    path: "{{ oneagent_installer_path }}"
  register: _oneagent_installer_stat

- name: Download OneAgent installer
  ansible.builtin.get_url:
    timeout: 60
    url: "{{ _oneagent_installer_url }}"
    dest: "{{ oneagent_installer_path }}"
    validate_certs: "{{ oneagent_validate_certs | default(true) }}"
    mode: "0755"
    headers:
      Authorization: Api-Token {{ oneagent_paas_token }}
  environment:
    SSL_CERT_FILE: "{{ oneagent_installer_download_cert | default(omit) }}"
  no_log: "{{ oneagent_no_log }}"
  ignore_errors: true
  register: _oneagent_download_result
  retries: 5
  until: _oneagent_download_result is succeeded
  delay: 10
  changed_when: false
